### ISSUE TITLE
Adding mypy checks

### ISSUE THREAD

**Issue by ChihChengLiang** [appliedzkp/zkevm-specs#114]
### Problem

As the python codebase grows, it might be a good idea to enforce the mypy checks for the consistency of types.

### Solution

- Add mypy dependency
- Add mypy check to Makefile
- Run the check in CI
- Fix all the typing errors (found 180 currently)

Better add it after #109 is complete to prevent duplicated work since it introduced many type changes.

**Comment by CPerezz** [comment]
I would have had appreciated a lot to have that after before working on #119 :rofl:

**Comment by HAOYUatHZ** [comment]
seems we can close this via https://github.com/appliedzkp/zkevm-specs/pull/132?
