### ISSUE TITLE
`CALLDATACOPY` should read caller's memory

### ISSUE THREAD

**Issue by han0110** [appliedzkp/zkevm-specs#134]
Currently `CALLDATACOPY` is implemented to read its own memory when `not is_root` (without `call_id` specified):

https://github.com/appliedzkp/zkevm-specs/blob/af758f49341fa11f2bc8d47a0e71d5b3eed1de13/src/zkevm_specs/evm/execution/memory_copy.py#L22-L33

We can fix this by extend the field `tx_id` of `CopyToMemoryAuxData` to `src_id`, to contain a `tx_id` when `from_tx`, and `caller_id` when `not from_tx`.

And with a slight change to the code above:

```diff
 for i in range(MAX_COPY_BYTES): 
     if not buffer_reader.read_flag(i): 
         byte = FQ.zero() 
     elif aux.from_tx == 1: 
         byte = instruction.tx_context_lookup( 
-            aux.tx_id, TxContextFieldTag.CallData, aux.src_addr + i
+            aux.src_id, TxContextFieldTag.CallData, aux.src_addr + i
         ) 
     else: 
-        byte = instruction.memory_lookup(RW.Read, aux.src_addr + i)
+        byte = instruction.memory_lookup(RW.Read, aux.src_addr + i, caller_id=aux.src_id)
     buffer_reader.constrain_byte(i, byte) 
     if buffer_reader.has_data(i): 
         instruction.constrain_equal(byte, instruction.memory_lookup(RW.Write, aux.dst_addr + i)) 
```

And `CALLDATACOPY` should also set the `src_id` correctly.

**Comment by icemelon** [comment]
I will address this in both spec and circuit

**Comment by CPerezz** [comment]
@icemelon was this addressed?
As it seems that in the circuits its not yet. See: https://github.com/appliedzkp/zkevm-circuits/pull/434

I think it isn't. And if so, would you take care? Or should re re-assign?

**Comment by roynalnaruto** [comment]
@CPerezz By mistake I mentioned to @icemelon that I had already addressed this, but the changes were not committed by me.

You can assign it to me, I'll handle this :)

**Comment by roynalnaruto** [comment]
@han0110 both PRs filed, linked above :)
