### ISSUE TITLE
Update `begin_Tx` & `end_tx` to constrain `TxReceipt`

### ISSUE THREAD

**Issue by DreamWuGit** [appliedzkp/zkevm-specs#177]
As `log_id` is defined as log index of each receipt/tx ,  need to ensure  state transition is valid besides in logs op code.  
In `begin_Tx` gadget, `log_id` should reset to zero at the beginning.
In `end_tx` gadget,  `log_id` should match with `LogLength` of `TxReceipt` RW table. if there is no log operations involved in tx,  it is zero as well.

**Comment by CPerezz** [comment]
Assigned it to you @DreamWuGit . 

Makes sense?

**Comment by DreamWuGit** [comment]
make sense !

**Comment by DreamWuGit** [comment]
also add other two fields of `TxReceipt`  :  `PostStateOrStatus` & `CumulativeGasUsed`:
(1) PostStateOrStatus should be equal to tx status in `end_tx`
(2) current receipt's `CumulativeGasUsed` =.pre receipt's `CumulativeGasUsed` + current tx gas cost

**Comment by ChihChengLiang** [comment]
closed by #181
