### ISSUE TITLE
Replace pasta curve in halo2 with kzg and bn curve 

### ISSUE THREAD

**Issue by ChihChengLiang** [appliedzkp/zkevm-specs#2]
### What's wrong

We want to be able to verify the proof with ETH l1 contract. pasta curve is too gas costly for that purpose.

We need to switch to kzg polynomial commitment and bn254 curve.

### How can we fix it

WIP from @kilic

**Comment by kilic** [comment]
In [pairing](https://github.com/kilic/pairing) repo we have bn256 pairing engine that uses same traits as halo2.

I also made kzg integration efford public [here](https://github.com/kilic/poly) that will be soon applied to the halo2 fork.

**Comment by kilic** [comment]
You can follow up to date version from [kilic/halo2](https://github.com/kilic/halo2/tree/kzg)

**Comment by ChihChengLiang** [comment]
Follow up here https://github.com/appliedzkp/zkevm-circuits/issues/38

**Comment by spartucus** [comment]
Hi, if we replace pasta curve with kzg and bn curve, is it possible to do recursive proof?

**Comment by ChihChengLiang** [comment]
@spartucus I don't think so. Do you still need recursive proof?

**Comment by spartucus** [comment]
Hi @ChihChengLiang , you mean in our zkEVM scheme, there is not need to use recursive proof? So for different contract all transactions, those are just different witness data with different lookup table? All the universal parts are just EVM circuit which handles opcode, byte circuit, MPT circuit, ECDSA circuit, etc.  Do I understand correctly?

**Comment by ChihChengLiang** [comment]
@spartucus we don't plan to use recursive proof.
IIUC, the lookup tables are part of the circuit. At the end of the day, we'll have gates and lookups, all in the form of polynomial commitment openings in kzg curve. We then have a proof aggregation circuit to turn those openings in a simple pairing check on the mainnet.

**Comment by spartucus** [comment]
> the lookup tables are part of the circuit.

Yes, lookup tables are part of circuit.

Great, I got the point. Thanks for your reply :)
