### ISSUE TITLE
add MaxCodeSize range check when program counter act as witness

### ISSUE THREAD

**Issue by DreamWuGit** [appliedzkp/zkevm-specs#70]
there is an MaxCodeSize limit for contract code bytes capacity in evm,  I realized  that we should constrain  such range  when pc as witness in the circuit , this can be implicitly property as op code itself maybe do not check it explicitly,   i.e. 'pc' op code.  
What do you think about it ? @ChihChengLiang  @han0110

**Comment by han0110** [comment]
The `program_counter` is always propagated between step, and the difference between step is always deterministic, so I think we don't need to worry about its range, right? If it's out of range, we should return a implicit `STOP` and the execution stops.

**Comment by DreamWuGit** [comment]
when i compose jump circuit, which takes me to consider the jump dest value validity affair,  this remind me of the MaxCodeSize limitation of evm as well as 'pc' op code.
 I am not sure if MaxCodeSize really does matter so far,  but I just add it in jump spec #67 for in case . put it here  to collect more ideas .

**Comment by han0110** [comment]
For `JUMP*`'s successful case, we don't need to explicitly verify if the destination is in range, the lookup already did for us (if out of range, we lookup nothing).

However, for invalid jump case, we need to verify 2 possible cases:

1. Destination is out of range
2. Destination is not a `JUMPDEST` or it's not annotated `is_code`

For the first case, we need the range lookup to compare them, and the maximum seems to be the maximum of the following two:

1. Max size of bytecode like you said - <code>3 * 2<sup>13</sup> (0x6000)</code>
2. Max size of transaction calldata as creation code - <code>≈2<sup>23</sup> (7486750)</code> (all zeros calldata with 30 million gas limit `(30000000-53000) / 4`)

So in worst case we need 3 bytes range lookup to verify that.

(btw the same range lookup is also requires for opcode like `CALLDATALOAD`, `CALLDATACOPY`, `CODECOPY`, `EXTCODECOPY`, `PUSH*`. Although `PUSH*` seems could be handled by padding of bytecode and tx table, but it seems to increase the overall complexity).

**Comment by ChihChengLiang** [comment]
Looks like this issue is resolved?
The JUMP and JUMPI have already indirectly enforced the MaxCodeSize range check. https://github.com/appliedzkp/zkevm-specs/blob/35e95d9970464e7fdc27440fa413ea4a17792b87/src/zkevm_specs/evm/execution/jump.py#L9-L10

Closing now, feel free to reopen if we have something to add.
